service: reservation-bot

provider:
  name: aws
  runtime: ruby2.7
  stackName: ${self:service}
  region: ${opt:region, 'ap-southeast-2'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - kms:Decrypt
        - kms:GenerateDatakey
      Resource: "${ssm:/reservationbot/kms.key.arn}"

functions:
  reservationbot:
    memorySize: 256
    name: ${self:service}
    handler: handler.Handler.action
    events:
    - http:
        path: "/action"
        method: post
        response:
          headers:
            Content-Type: "application/json"
            X-Slack-No-Retry: "1"
    environment:
      VERIFICATION_TOKEN: ${ssm:/reservationbot/slack.verification.token}
      BOT_TOKEN: ${ssm:/reservationbot/slack.bot.oauth.token}
